sudo: required
language: node_js
node_js:
  - "stable"

services:
  - docker

before_install:
  # install heroku CLI
 # - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  #- echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

#jdk:
  #- oraclejdk8

#addon:
 # sonarcloud: true

script:
  - npm test
  # sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=majo1569 -Dsonar.projectKey=majo1569_suma-ci -Dsonar.sources='./app' -X
  - docker build -t majo69/ci-image .
  #docker tag majo69/ci-image 
    #registry.heroku.com/$HEROKU_APP_NAME/web

#notifications:
  #slack: trabajodeis:Giyiq8DAlvuWDB4aV3Lb1s3v


deploy:
  provider: script
  script:
    # push to dockerhub
    docker push majo69/ci-image;
    #docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    #heroku container:release web --app $HEROKU_APP_NAME  
 