sudo: required
language: node_js
node_js:
  - "stable"
services:
  - docker
before_install:
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
install:
  # install deps
  - yarn install
jdk:
  - oraclejdk8
script:
  - yarn test
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=majo1569-github -Dsonar.projectKey=majo1569_suma-ci -Dsonar.sources='./app' -X
  - yarn build
  # build docker images
  - docker build -t majo69/ci-image .
addons:
  sonarcloud: true

  
deploy: 
  provider: script
  script:
    docker push majo69/ci-image;
  branch: main




    
